{
 "title": "Eventlog service",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Health",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "eventlog_service_health" }
   ]
  },
  {
   "title": "Messages received / min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(eventlog_service_count_messagereceived_total[10s])*60"
    }
   ]
  },
  {
   "title": "Eventlog service CPU utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "process_cpu_usage{job=\"eventlog-service\"}*100"
    }
   ]
  },
  {
   "title": "Execution time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "eventlog_service_avgexecutiontime_messagereceived_ms"
    }
   ]
  },
  {
   "title": "Consumer lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "eventlog_service_consumerlag_pcs"
    }
   ]
  }
 ]
}